### ISSUE TITLE
Expose IPFS Core API as window.ipfs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/in-web-browsers#42] opened 2017-02-15 20:49 UTC
Web Extension makes **js-ipfs** protocol (interface-core-api) available in the browser through window.ipfs
  * creates an instance of js-ipfs inside the extension (see #12)
  * exposes that  instance directly in window.ipfs
  * this will expose the same API as #41, since both implement interface-ipfs-core
  * like #41, using the core api vs relying on the gateway should be disabled/enabled by toggling a "Redirect-URLs" option true or false
  * disable by default

**Comment by haadcode** [comment] 2017-02-21 15:19
I did a quick prototype for this today: load js-ipfs packaged with the extension, start an instance.

Challenges here are similar to https://github.com/ipfs/in-web-browsers/issues/41.

- Loading the js-ipfs script inside the extension and exposing it at window.ipfs is trivial
- Starting the js-ipfs works, **but...**
- Can't connect to a signaling server (wss://) due to the Content Security Policy which requires remote sources to be https:// (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy)

**Comment by haadcode** [comment] 2017-02-21 15:37
So basically as far as I can tell, the js-ipfs instance in the extension can't communicate to anyone except via https. Adding files, etc. would work normally, but an IPFS node without a network is fairly limited in functionality...

**Comment by VictorBjelkholm** [comment] 2017-02-21 15:47
I got something working over here: https://github.com/VictorBjelkholm/js-ipfs-in-the-browser

Basically it sets up two parts. One background page for the daemon and handling communication with the content script. Two is the content script that injects functions to the page script.

You can download and install this: https://github.com/VictorBjelkholm/js-ipfs-in-the-browser/releases/tag/lol

When installed, this page should change from "nope" -> "yeah!" and also show your daemons id: https://ipfs.io/ipfs/QmcVc8eQiWkR23wMKiQjipLRSjCxR1FEj4TL99aY89J83d

**Comment by haadcode** [comment] 2017-02-21 16:20
Great work @VictorBjelkholm! 🎉

**Comment by VictorBjelkholm** [comment] 2017-02-21 17:30
After standup call, I'll do the following before moving on:

- [ ] Expose:
  - [ ] `.cat`
  - [ ] `.add`
  - [ ] `.ls`
  - [ ] `.swarm.peers`
  - [ ] `.dag.put`
  - [ ] `.dag.get`
  - [ ] `.files.cat`

**Comment by VictorBjelkholm** [comment] 2017-02-21 17:32
@haadcode maybe you could list the methods you're using in Orbit, and we could get Orbit to work with the extension instance of js-ipfs? I'm betting the shipping JS without js-ipfs/js-ipfs-api would be minimal and load super fast!

**Comment by haadcode** [comment] 2017-02-22 15:38
@VictorBjelkholm orbit is using .object.put/.get, .pubsub (pretty much all methods), .swarm.peers and .files.add/.cat. And the Electron version uses those + .util.addFromFs and .ls.

**Comment by flyingzumwalt** [comment] 2017-02-22 17:45
Can I add a request that we document how to get at the other API methods?  For example, if I want to use `ipfs.dht.findProvs` but it hasn't been added by the web extension, how can I connect to ipfs and consume that API method? What libraries do I need to download? Do I need to initialize a separate connection to the ipfs daemon? etc...

**Comment by VictorBjelkholm** [comment] 2017-02-23 15:06
So, trouble in wonderland. Seemingly, you cannot pass functions or anything that can't be serialized into JSON between the background and content scripts.

This makes the interface of for example `.cat` to be broken, since we would only be able to pass the finalized data rather than a stream with the data...

Not sure how to solve this, but reached out in Mozilla IRC about confirmation and help with workarounds if possible.

**Comment by Kubuxu** [comment] 2017-02-23 16:55
@VictorBjelkholm it is intended behaviour as the background and content scripts might run in separate JS engine instances.

**Comment by lgierth** [comment] 2017-04-18 14:41
Probably the next steps here are:

- Expand Core API coverage of `window.ipfs`
- Investigate whether `window.ipfs` is the appropriate place
- Integrate into @lidel's webext: https://github.com/lidel/ipfs-firefox-addon

**Comment by lidel** [comment] 2018-01-02 12:48
FYSA we hope to deliver this feature via browser extension (it will be an opt-in experiment initially)
Implementation progress can be tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/330

**Comment by lidel** [comment] 2018-03-06 12:33
This feature landed in Beta channel of our browser extension. Check Release Notes for [v2.2.0beta2](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.2.0beta2).

Discussion continues in https://github.com/ipfs-shipyard/ipfs-companion/issues/330

**Closed by lidel** 2018-03-06 12:33 UTC
Labels: developers, ready, web extension
